name: Send a telegram message when new hot subreddit
on:
  reddit:
    url: https://www.reddit.com/r/hearthstone/
    #source: json
    every: 0
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <a href="${{on.reddit.outputs.link}}">${{ on.reddit.outputs.title }}</a>
            ${{on.reddit.outputs.contentSnippet}}
            ${{on.reddit.outputs.pubDate}}
