on:
  script:
    run: |
      let items = [Math.random()*10];
      return items;
    config:
      every: 0
      #every: "* 12 * * *"
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '*/15 * * * *'
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            #The ${{ github.event_name }} event triggered final step.
            *bold text*
            _italic text_
            __underline__
            ~strikethrough~
            *bold _italic bold ~italic bold strikethrough~ __underline italic bold___ bold*
            [тест Ряяя](http://www.example.com/)
            [inline\[тест\] URL](http://www.example.com/)
            [inline mention of a user](tg://user?id=123456789)
            `inline fixed-width code`
            ```
            pre-formatted fixed-width code block
            ```
            ```python
            pre-formatted fixed-width code block written in the Python programming language
            ```